difference_and_sum: difference_and_sum.o my_function.o 
	gcc -ansi -pedantic -Wall difference_and_sum.o my_function.o -o difference_and_sum

difference_and_sum.o: difference_and_sum.c
	gcc -c -ansi -pedantic -Wall difference_and_sum.c -o difference_and_sum.o
	
my_function.o: my_function.c
	gcc -c -ansi -pedantic -Wall my_function.c -o my_function.o
	
